[package]
name = "bevy_tilemap_core"
version = "0.4.0"
authors = ["Joshua J. Bouw <dev@joshuajbouw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.4"
bevy_asset = "0.4"
bevy_ecs = "0.4"
bevy_log = "0.4"
bevy_math = "0.4"
bevy_reflect = "0.4"
bevy_render = "0.4"
bevy_sprite = "0.4"
bevy_tilemap_types = { path = "../types", version = "0.4" }
bevy_transform = "0.4"
bevy_utils = "0.4"
bevy_window = "0.4"
